"""test upgrade

Revision ID: 360f49391d4b
Revises: a95b9f4a53ab
Create Date: 2020-01-12 20:35:20.442254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360f49391d4b'
down_revision = 'a95b9f4a53ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
