"""test upgrade2

Revision ID: e25df8ac213e
Revises: 360f49391d4b
Create Date: 2020-01-12 20:36:28.205679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25df8ac213e'
down_revision = '360f49391d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
